### ISSUE TITLE
Elastic/Kibana not pulling any data

### ISSUE THREAD

**Issue by incodia-ash** [ukncsc/lme#131]
Perhaps I have failed to complete a step or such but whenever I launch and login to view the Elastic dashboard and look at the analytics pages I get numerous errors for missing fields and such.

![image](https://user-images.githubusercontent.com/99304323/153382980-4e064ff2-8ca1-4755-aba9-a33fa63f3110.png)

![image](https://user-images.githubusercontent.com/99304323/153383055-59cb9c77-70ac-4dab-a22a-f59c59683220.png)

The winlogbeat service is running on the Windows Event Collector server so unsure if it's a communication issue between the two perhaps? (I can ping the LME server from the WEC server)

**Comment by ghost** [comment]
I am also having this same issue

**Comment by philshil** [comment]
Also experiencing the same issue. Fresh install today.

**Comment by adam-ncc** [comment]
Hi @incodia-ash, as you've said it looks as though you don't have any data in elasticsearch for some reason, which is why there are errors in the dashboards. There could be a number of reasons for this, so it's probably worth walking through the checklists of Chapters 1-3 of the install instructions ([here](https://github.com/ukncsc/lme/blob/master/docs/chapter1.md#chapter-1---checklist), [here](https://github.com/ukncsc/lme/blob/master/docs/chapter2.md), and [here](https://github.com/ukncsc/lme/blob/master/docs/chapter3.md#chapter-3---checklist)), primarily to make sure that there are actually events within the Windows Event Collector's Forwarded Events channel, as it's possible that logs are being correctly forwarded by the WEC server has no logs to send if this part isn't properly configured.

If you've verified that there are logs within the Forwarded Events channel you'd expect to be seeing in Elastic, then the next step would be to check the winlogbeat and logstash logs to see if there's any sort of obvious communication errors between the two, or anything that may indicate why the data is not being sent correctly. The relevant log locations and how to query them can be found in the table available [here](https://github.com/ukncsc/lme/blob/master/docs/troubleshooting.md). 

Let me know how you get on, and if you can confirm whether you have logs that should be forwarded but are not being, and we can go from there.

Thanks.

**Comment by incodia-ash** [comment]
Hi Adam,

Thanks for getting back.

Have confirmed that the windows event collection is set up and configured correctly, have followed the steps on 1,2 and 3 as what I can only say is to the letter.

![image](https://user-images.githubusercontent.com/99304323/157415802-5bd2986d-586a-467e-80cc-5323a5244cd3.png)

WinLogBeat Logs

2022-03-09T10:13:17.656Z	INFO	[monitoring]	log/log.go:184	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":265,"time":{"ms":16}},"total":{"ticks":1358,"time":{"ms":16},"value":1358},"user":{"ticks":1093}},"handles":{"open":234},"info":{"ephemeral_id":"80bc2d75-913c-41f3-8d2b-7e48b1391e49","uptime":{"ms":120144},"version":"7.16.3"},"memstats":{"gc_next":91844816,"memory_alloc":70934968,"memory_total":244284376,"rss":117694464},"runtime":{"goroutines":21}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"active":0},"read":{"bytes":2291},"write":{"bytes":282}},"pipeline":{"clients":1,"events":{"active":4117,"retry":2048}}}}}}
2022-03-09T10:13:38.033Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://inclinuxlme.incodia.co.uk:5044)): x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "Swarm")
2022-03-09T10:13:38.033Z	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(async(tcp://inclinuxlme.incodia.co.uk:5044)) with 7 reconnect attempt(s)
2022-03-09T10:13:38.034Z	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer

Seems to be a connection based error, but I'm a little bit of a loss as the event collection server is resolving the name (I can ping the name for example) and have configured firewall policies to explicitly allow connection between the servers.

Any ideas?

**Comment by duncan-ncc** [comment]
Hi @incodia-ash, 

That certificate error suggests that your winlogbeat.yml config does not have the root-ca.crt defined in it, or the root-ca.crt file is not present in the location specified as outlined in this section of the installation instructions. The WLB machine needs to be able to trust and verify the LME certificates generated during install on the linux box.

[3.3.2 - Install Winlogbeat & Certificates](https://github.com/ukncsc/lme/blob/master/docs/chapter3.md#332-install-winlogbeat)

**Comment by incodia-ash** [comment]
![image](https://user-images.githubusercontent.com/99304323/157626062-21af7756-1380-4a68-9365-879f2b7016a6.png)

The files are present and were copied over as per the steps written down so am a little confused by this... any recommendations on remediation steps?

**Comment by adam-ncc** [comment]
Hey @incodia-ash, thanks for checking that - just to make sure, would you be able to check that ```winlogbeat.yml``` file is also inside the ```winlogbeat-7.16.3-windows-x86_64``` folder, and then post the contents of that file with the hostname redacted here for us to have a look at? This will help us work out if the error is in the configuration itself or in the generated certificate.

![image](https://user-images.githubusercontent.com/52567990/157653533-d27fd61d-73b3-4174-bc68-e8c52746f5ec.png)

Can I also ask, did you have the installer generate self-signed certificates (I’m assuming yes based on the information we have so far), or did you provide it pre-generated certificates to use?

**Comment by incodia-ash** [comment]
So can confirm that the winlogbeat file is in both directories.

File info below

```
winlogbeat.event_logs:
  - name: ForwardedEvents
    tags: [forwarded]
    processors:
      - script:
          when.equals.winlog.channel: Security
          lang: javascript
          id: security
          file: ${path.home}/module/security/config/winlogbeat-security.js
      - script:
          when.equals.winlog.channel: Microsoft-Windows-Sysmon/Operational
          lang: javascript
          id: sysmon
          file: ${path.home}/module/sysmon/config/winlogbeat-sysmon.js
  
output.logstash:
  hosts: ["*.co.uk:5044"]
  ssl.certificate_authorities: ["C:\\Program Files\\lme\\root-ca.crt"]
  ssl.certificate: "C:\\Program Files\\lme\\wlbclient.crt"
  ssl.key: "C:\\Program Files\\lme\\wlbclient.key"
```

The certificates and files were generated using the installer, nothing pre-configured.
