### ISSUE TITLE
Winlogbeat cannot access ELK Server

### ISSUE THREAD

**Issue by TiggBloomz** [ukncsc/lme#19]
Hi,

Firstly, thank you for compiling all of these resources to create LME.

I've followed all of the steps (I think correctly). I'm currently stuck around Step 3 (Easy).
 
Unfortunately, winlogbeat cannot sent logs to the ELK ubuntu server. I keep getting the following errors:

```
[2019-05-14T12:59:33.771+0100	INFO	pipeline/output.go:95	Connecting to backoff(async(tcp://elk:5044))
2019-05-14T12:59:36.947+0100	ERROR	pipeline/output.go:100	Failed to connect to backoff(async(tcp://elk:5044)): read tcp 10.0.210.85:51912->10.0.210.100:5044: wsarecv: An existing connection was forcibly closed by the remote host.]
```

I've binned the ubuntu server a few times and started again, to no avail.. I can, however, access Kibana fine. 

One thing I did notice in running the "deploy.sh" script is that it asks the following:

```
Enter the IP that winlogbeat will use to communicate with this box:
Enter the DNS name that winlogbeat uses to communicate with this box: 
```
For the above, do I insert the IP and DNS of the Windows Event Collector VM, or the details of the ELK server? Apologies if this is blatantly obvious.

To troubleshoot, I've turned off the firewall on both the Ubuntu server and the Windows Log Collector VM, to no avail.

Contents of the winlogbeat.yml, FYI:

```
winlogbeat.event_logs:
  - name: ForwardedEvents
output.logstash:
  hosts: ["elk:5044"]
  ssl.certificate_authorities: ["C:\\Program Files\\lme\\root-ca.crt"]
  ssl.certificate: "C:\\Program Files\\lme\\wlbclient.crt"
  ssl.key: "C:\\Program Files\\lme\\wlbclient.key"
```

"elk" is also registered in DNS.

Can you help?

Thanks in advance.
